import {Inter} from 'next/font/google'
import Header from '../components/shared/header/src/Header.jsx'
import Footer from '../components/shared/footer/src/Footer.jsx'
import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header type={'header-home'} />
        <Footer type={'footer-home'} />
        {children} {/* Asegúrate de renderizar los hijos */}
      </body>
    </html>
  )
}
