import {Inter} from 'next/font/google'
import Header from '../components/header/src/Header.jsx'
import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <head>
        {/* Aquí puedes agregar cualquier elemento adicional en el head si es necesario */}
      </head>
      <body className={inter.className}>
        <Header />
        {children} {/* Asegúrate de renderizar los hijos */}
      </body>
    </html>
  )
}
